// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdyzXjWxDckZfvpSj3Jo3nflXSbGCqhwo',
    appId: '1:251069410985:web:56c8f6fbb4a62d65b183b8',
    messagingSenderId: '251069410985',
    projectId: 'chat-app-c5ba2',
    authDomain: 'chat-app-c5ba2.firebaseapp.com',
    storageBucket: 'chat-app-c5ba2.appspot.com',
    measurementId: 'G-K5P61THQZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATe0jXYz0Pco6qtcwrFuzk_MjGbqReCfE',
    appId: '1:251069410985:android:e88a0d1be8ebb7a2b183b8',
    messagingSenderId: '251069410985',
    projectId: 'chat-app-c5ba2',
    storageBucket: 'chat-app-c5ba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe8tl23SFWQAe2dMjAaP6ZCPXoP1rEwmQ',
    appId: '1:251069410985:ios:db9fefb79c70166bb183b8',
    messagingSenderId: '251069410985',
    projectId: 'chat-app-c5ba2',
    storageBucket: 'chat-app-c5ba2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe8tl23SFWQAe2dMjAaP6ZCPXoP1rEwmQ',
    appId: '1:251069410985:ios:db9fefb79c70166bb183b8',
    messagingSenderId: '251069410985',
    projectId: 'chat-app-c5ba2',
    storageBucket: 'chat-app-c5ba2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdyzXjWxDckZfvpSj3Jo3nflXSbGCqhwo',
    appId: '1:251069410985:web:41d3c9525bc824eab183b8',
    messagingSenderId: '251069410985',
    projectId: 'chat-app-c5ba2',
    authDomain: 'chat-app-c5ba2.firebaseapp.com',
    storageBucket: 'chat-app-c5ba2.appspot.com',
    measurementId: 'G-F87XMMSK1E',
  );

}